import { Platform, Game, CollectionItem, TimelineEvent } from './types';

// ─── PLATFORMS (10+) ──────────────────────────────────────────────────────────

export const platforms: Platform[] = [
  {
    id: 'magnavox',
    name: 'Magnavox Odyssey',
    manufacturer: 'Magnavox',
    releaseYear: 1972,
    discontinuedYear: 1975,
    generation: '1세대 (1972–1980)',
    era: '1st Gen (1972-1980)',
    color: '#8B7355',
    imageUrl: '',
    description: '세계 최초의 가정용 비디오 게임 콘솔. Ralph Baer가 설계했으며 12개의 게임 카드를 지원했다.',
    innovationPoint: '가정에서 TV로 게임을 즐기는 시대의 포문을 열다',
    unitsSoldMillions: 0.35,
  },
  {
    id: 'atari2600',
    name: 'Atari 2600',
    manufacturer: 'Atari',
    releaseYear: 1977,
    discontinuedYear: 1992,
    generation: '2세대 (1976–1992)',
    era: '2nd Gen (1976-1992)',
    color: '#8B4513',
    imageUrl: '',
    description: '교체형 ROM 카트리지 시스템으로 게임기 시장을 대중화한 선구자. 30M 장 이상 판매.',
    innovationPoint: 'ROM 카트리지 교체 시스템 도입으로 소프트웨어 생태계 창출',
    unitsSoldMillions: 30,
    cpuSpec: 'MOS 6507 @ 1.19 MHz',
  },
  {
    id: 'nes',
    name: 'NES / Famicom',
    manufacturer: 'Nintendo',
    releaseYear: 1983,
    discontinuedYear: 2003,
    generation: '3세대 (1983–2003)',
    era: '3rd Gen (1983-2003)',
    color: '#C41E3A',
    imageUrl: '',
    description: '비디오 게임 대붕괴(1983) 이후 산업을 부활시킨 전설적 콘솔. 61.9M 대 판매.',
    innovationPoint: 'D-패드와 A/B 버튼 배치의 표준화, 라이선스 제도로 품질 관리',
    unitsSoldMillions: 61.9,
    cpuSpec: 'Ricoh 2A03 @ 1.79 MHz',
  },
  {
    id: 'sega_genesis',
    name: 'Sega Genesis / Mega Drive',
    manufacturer: 'Sega',
    releaseYear: 1988,
    discontinuedYear: 1997,
    generation: '4세대 (1987–2004)',
    era: '4th Gen (1987-2004)',
    color: '#1a1a2e',
    imageUrl: '',
    description: '"블래스트 프로세싱"과 소닉으로 닌텐도에 맞선 16비트 경쟁자. 30.75M 대 판매.',
    innovationPoint: '16비트 성능과 빠른 스크롤로 아케이드 이식 품질 혁신',
    unitsSoldMillions: 30.75,
    cpuSpec: 'Motorola 68000 @ 7.67 MHz',
  },
  {
    id: 'gameboy',
    name: 'Game Boy',
    manufacturer: 'Nintendo',
    releaseYear: 1989,
    discontinuedYear: 2003,
    generation: '4세대 (1987–2004)',
    era: '4th Gen (1987-2004)',
    color: '#7B8D6E',
    imageUrl: '',
    description: '휴대용 게임기의 표준을 제시한 혁신적 기기. 테트리스 번들로 118.69M 대 판매.',
    innovationPoint: '장시간 AA건전지 구동, 통신 케이블로 멀티플레이 혁신',
    unitsSoldMillions: 118.69,
    cpuSpec: 'Sharp LR35902 @ 4.19 MHz',
  },
  {
    id: 'sfc',
    name: 'Super Famicom / SNES',
    manufacturer: 'Nintendo',
    releaseYear: 1990,
    discontinuedYear: 2003,
    generation: '4세대 (1987–2004)',
    era: '4th Gen (1987-2004)',
    color: '#6B6B9E',
    imageUrl: '',
    description: '16비트 시대를 대표하는 명기. RPG의 황금기를 열다. 49.1M 대 판매.',
    innovationPoint: 'Mode 7 회전/확대 효과, Sony SPC700 사운드 칩으로 음질 혁신',
    unitsSoldMillions: 49.1,
    cpuSpec: 'WDC 65C816 @ 3.58 MHz',
  },
  {
    id: 'ps1',
    name: 'PlayStation',
    manufacturer: 'Sony',
    releaseYear: 1994,
    discontinuedYear: 2006,
    generation: '5세대 (1993–2006)',
    era: '5th Gen (1993-2006)',
    color: '#003087',
    imageUrl: '',
    description: 'CD-ROM 기반으로 3D 게임의 시대를 연 혁명적 콘솔. 102.49M 대 판매.',
    innovationPoint: 'CD-ROM으로 대용량 저장, 실시간 3D 폴리곤 렌더링 대중화',
    unitsSoldMillions: 102.49,
    cpuSpec: 'MIPS R3000A @ 33.9 MHz',
  },
  {
    id: 'n64',
    name: 'Nintendo 64',
    manufacturer: 'Nintendo',
    releaseYear: 1996,
    discontinuedYear: 2002,
    generation: '5세대 (1993–2006)',
    era: '5th Gen (1993-2006)',
    color: '#2D2D2D',
    imageUrl: '',
    description: '아날로그 스틱과 3D 게임의 혁신을 주도한 64비트 콘솔. 32.93M 대 판매.',
    innovationPoint: '아날로그 스틱, 트리거 버튼, 럼블 팩으로 3D 조작 표준화',
    unitsSoldMillions: 32.93,
    cpuSpec: 'NEC VR4300 @ 93.75 MHz',
  },
  {
    id: 'dc',
    name: 'Dreamcast',
    manufacturer: 'Sega',
    releaseYear: 1998,
    discontinuedYear: 2001,
    generation: '6세대 (1998–2013)',
    era: '6th Gen (1998-2013)',
    color: '#FF6B00',
    imageUrl: '',
    description: '시대를 앞서간 온라인 게임 선구자. 내장 모뎀으로 인터넷 연결. 9.13M 대 판매.',
    innovationPoint: '내장 56k 모뎀으로 콘솔 온라인 게임 개척, VMU 서브 스크린',
    unitsSoldMillions: 9.13,
    cpuSpec: 'Hitachi SH-4 @ 200 MHz',
  },
  {
    id: 'ps2',
    name: 'PlayStation 2',
    manufacturer: 'Sony',
    releaseYear: 2000,
    discontinuedYear: 2013,
    generation: '6세대 (1998–2013)',
    era: '6th Gen (1998-2013)',
    color: '#00439C',
    imageUrl: '',
    description: '역대 가장 많이 팔린 게임 콘솔. DVD 재생 기능으로 대중 문화 아이콘이 되다. 155M 대 판매.',
    innovationPoint: 'DVD 플레이어 + 후방 호환성, Emotion Engine으로 실시간 영화급 그래픽',
    unitsSoldMillions: 155,
    cpuSpec: 'MIPS R5900 (Emotion Engine) @ 294 MHz',
  },
  {
    id: 'nds',
    name: 'Nintendo DS',
    manufacturer: 'Nintendo',
    releaseYear: 2004,
    discontinuedYear: 2013,
    generation: '7세대 (2005–2017)',
    era: '7th Gen (2005-2017)',
    color: '#A8A8A8',
    imageUrl: '',
    description: '듀얼 스크린과 터치 조작으로 게임의 가능성을 넓히다. 154.02M 대 판매.',
    innovationPoint: '듀얼 스크린, 터치 입력, 마이크, 무선 통신의 통합 혁신',
    unitsSoldMillions: 154.02,
    cpuSpec: 'ARM946E-S @ 67 MHz',
  },
  {
    id: 'switch',
    name: 'Nintendo Switch',
    manufacturer: 'Nintendo',
    releaseYear: 2017,
    generation: '8세대 (2012–2020)',
    era: '8th Gen (2012-2020)',
    color: '#E60012',
    imageUrl: '',
    description: '거치형과 휴대형의 경계를 허문 하이브리드 게임기. 140M+ 대 판매 중.',
    innovationPoint: 'TV 도킹 + 휴대 모드 전환, Joy-Con 분리합체로 다양한 플레이 스타일',
    unitsSoldMillions: 141,
    cpuSpec: 'NVIDIA Tegra X1 @ 1.02 GHz',
  },
];

/** 구형 호환용 alias */
export const consoles = platforms;

// ─── GAMES (40+) ──────────────────────────────────────────────────────────────

export const games: Game[] = [
  // ── Atari 2600 ──
  {
    id: 'g01',
    title: 'Pitfall!',
    releaseYear: 1982,
    releaseDate: '1982-04-20',
    platform: 'Atari 2600',
    genre: 'Platformer',
    country: 'US',
    developer: 'David Crane (Activision)',
    publisher: 'Activision',
    era: '2nd Gen (1976-1992)',
    imageUrl: '',
    description: '초기 플랫포머의 걸작. Activision의 David Crane이 개발하여 400만 장 이상 판매된 Atari 2600 시대의 대표작.',
    historicalContext: '아타리 2600의 한계인 128바이트 RAM을 기막히게 활용한 기술적 성취의 결정체.',
    historicalNote: '400만 장 이상 판매된 Activision의 최대 히트작',
    relatedEvents: [{ year: 1980, description: 'Activision 창설, 아타리 전 직원들이 독립' }],
    competingPlatforms: ['Atari 5200', 'ColecoVision'],
    popularity: 65,
    rating: 3.8,
    rarity: 'Common',
  },
  {
    id: 'g02',
    title: 'Adventure',
    releaseYear: 1980,
    releaseDate: '1980-01-01',
    platform: 'Atari 2600',
    genre: 'Adventure',
    country: 'US',
    developer: 'Warren Robinett (Atari)',
    publisher: 'Atari',
    era: '2nd Gen (1976-1992)',
    imageUrl: '',
    description: '최초의 액션 어드벤처 게임이자 최초의 이스터 에그를 포함한 역사적 타이틀.',
    historicalContext: '개발자 Warren Robinett이 크레딧을 받지 못하자 비밀 방에 자신의 이름을 숨겨넣은 최초의 이스터 에그.',
    popularity: 55,
    rating: 3.5,
    rarity: 'Uncommon',
  },
  {
    id: 'g03',
    title: 'E.T. the Extra-Terrestrial',
    releaseYear: 1982,
    releaseDate: '1982-12-01',
    platform: 'Atari 2600',
    genre: 'Adventure',
    country: 'US',
    developer: 'Howard Scott Warshaw (Atari)',
    publisher: 'Atari',
    era: '2nd Gen (1976-1992)',
    imageUrl: '',
    description: '게임 역사상 가장 악명 높은 실패작. 뉴멕시코 사막에 매립된 전설의 게임.',
    historicalContext: '단 5주 만에 제작된 이 게임은 1983년 비디오 게임 대붕괴의 상징이 되었다. 2014년 뉴멕시코 매립지에서 실제로 발굴됨.',
    popularity: 72,
    rating: 1.5,
    rarity: 'Rare',
  },

  // ── NES / Famicom ──
  {
    id: 'g04',
    title: 'Super Mario Bros.',
    releaseYear: 1985,
    releaseDate: '1985-09-13',
    platform: 'NES',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Nintendo R&D4',
    publisher: 'Nintendo',
    developerLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Nintendo.svg/600px-Nintendo.svg.png',
    era: '3rd Gen (1983-2003)',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Super_Mario_Bros._box.png/220px-Super_Mario_Bros._box.png',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/0/03/Super_Mario_Bros._box.png',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Super_Mario_Bros._Logo.svg/200px-Super_Mario_Bros._Logo.svg.png'
    ],
    description: '비디오 게임 역사를 바꾼 불멸의 걸작. 사이드스크롤 플랫포머의 교과서.',
    historicalContext: '패미컴의 번들 타이틀로 시작해 전 세계 4,024만 장을 판매. 미야모토 시게루의 대표작.',
    historicalNote: '4,024만 장 이상 판매된 역대 최다 판매 게임 중 하나',
    relatedEvents: [{ year: 1983, description: 'Famicom 발매, 가정용 게임기 부활의 신호탄' }],
    competingPlatforms: ['Atari 7800', 'Sega Master System'],
    sameEraGames: ['g05', 'g06', 'g07'],
    popularity: 98,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g05',
    title: 'The Legend of Zelda',
    releaseYear: 1986,
    releaseDate: '1986-02-21',
    platform: 'NES',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Nintendo R&D4',
    publisher: 'Nintendo',
    era: '3rd Gen (1983-2003)',
    imageUrl: '',
    description: '오픈월드 어드벤처의 시초. 배터리 백업으로 세이브 기능을 최초 도입.',
    historicalContext: '금색 카트리지와 배터리 백업 세이브 시스템으로 게임의 볼륨을 한 차원 높였다.',
    popularity: 92,
    rating: 4.8,
    rarity: 'Uncommon',
  },
  {
    id: 'g06',
    title: 'Mega Man 2',
    releaseYear: 1988,
    releaseDate: '1988-12-24',
    platform: 'NES',
    genre: 'Action',
    country: 'JP',
    developer: 'Capcom',
    publisher: 'Capcom',
    era: '3rd Gen (1983-2003)',
    imageUrl: '',
    description: '시리즈 최고의 걸작으로 평가받는 액션 게임. 완벽한 난이도와 음악의 조화.',
    historicalContext: '이노우에 타케시 작곡의 사운드트랙은 오늘날까지 게임 음악의 명곡으로 꼽힌다.',
    popularity: 88,
    rating: 4.7,
    rarity: 'Uncommon',
  },
  {
    id: 'g07',
    title: 'Castlevania',
    releaseYear: 1986,
    releaseDate: '1986-09-26',
    platform: 'NES',
    genre: 'Action',
    country: 'JP',
    developer: 'Konami',
    publisher: 'Konami',
    era: '3rd Gen (1983-2003)',
    imageUrl: '',
    description: '고딕 호러 액션의 원조. 메트로배니아 장르의 기원이 된 시리즈의 첫 작품.',
    historicalContext: '드라큘라 성을 배경으로 한 고딕 미학과 도전적 난이도로 장르의 틀을 세웠다.',
    popularity: 85,
    rating: 4.5,
    rarity: 'Uncommon',
  },
  {
    id: 'g08_contra',
    title: 'Contra',
    releaseYear: 1987,
    releaseDate: '1987-02-20',
    platform: 'NES',
    genre: 'Run & Gun',
    country: 'JP',
    developer: 'Konami',
    publisher: 'Konami',
    era: '3rd Gen (1983-2003)',
    imageUrl: '',
    description: '코나미 코드의 전설이 탄생한 2인 협동 슈팅 게임의 교과서.',
    historicalContext: '↑↑↓↓←→←→BA — 역사상 가장 유명한 치트 코드의 탄생지.',
    popularity: 87,
    rating: 4.6,
    rarity: 'Common',
  },

  // ── Game Boy ──
  {
    id: 'g08',
    title: 'Tetris',
    releaseYear: 1989,
    releaseDate: '1989-06-14',
    platform: 'Game Boy',
    genre: 'Puzzle',
    country: 'SU', // 소련
    developer: 'Nintendo / Alexey Pajitnov',
    publisher: 'Nintendo',
    developerLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Nintendo.svg/600px-Nintendo.svg.png',
    era: '4th Gen (1987-2004)',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/NES_Tetris_Box_Front.jpg/220px-NES_Tetris_Box_Front.jpg',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/8/8d/NES_Tetris_Box_Front.jpg'
    ],
    description: '게임보이를 세계적 히트로 만든 퍼즐의 제왕. 소련에서 탄생한 글로벌 문화 현상.',
    historicalContext: '소련 과학자 Alexey Pajitnov가 만든 게임. 닌텐도와의 라이선스 전쟁은 게임 산업 역사의 한 페이지.',
    popularity: 97,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g09',
    title: 'Pokémon Red / Blue',
    releaseYear: 1996,
    releaseDate: '1996-02-27',
    platform: 'Game Boy',
    genre: 'RPG',
    country: 'JP',
    developer: 'Game Freak',
    publisher: 'Nintendo',
    developerLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Game_Freak_logo.svg/320px-Game_Freak_logo.svg.png',
    publisherLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Nintendo.svg/600px-Nintendo.svg.png',
    era: '4th Gen (1987-2004)',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Bulbasaur_pokemon_red.png/220px-Bulbasaur_pokemon_red.png',
    screenshots: [
      'https://upload.wikimedia.org/wikipedia/en/f/f1/Bulbasaur_pokemon_red.png',
      'https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Pokemon_Red_and_Blue_box_arts.png/220px-Pokemon_Red_and_Blue_box_arts.png'
    ],
    description: '포켓몬 프랜차이즈의 시작. 수집과 교환의 혁신적 게임플레이로 사회 현상을 일으키다.',
    historicalContext: '다나카 히데키 / 모리미야 켄타로의 6년 개발. 2세대 통신 케이블 교환 메커닉이 전 세계 어린이를 연결했다.',
    popularity: 95,
    rating: 4.8,
    rarity: 'Common',
  },
  {
    id: 'g10',
    title: "The Legend of Zelda: Link's Awakening",
    releaseYear: 1993,
    releaseDate: '1993-06-06',
    platform: 'Game Boy',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '휴대용 기기에서도 풀 스케일 젤다 경험을 구현한 명작.',
    historicalContext: '마리오, 커비 등 닌텐도 캐릭터가 카메오 출연하는 이례적인 작품. 꿈의 섬 설정이 시리즈 내 독보적 위상.',
    popularity: 82,
    rating: 4.6,
    rarity: 'Uncommon',
  },

  // ── Sega Genesis ──
  {
    id: 'g_sonic1',
    title: 'Sonic the Hedgehog',
    releaseYear: 1991,
    releaseDate: '1991-06-23',
    platform: 'Sega Genesis',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Sonic Team (Sega)',
    publisher: 'Sega',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '세가의 마스코트 소닉의 탄생. 속도를 전면에 내세운 플랫포머의 새 패러다임.',
    historicalContext: '닌텐도 마리오에 대항하기 위해 만든 세가의 切牌. 속도와 과감한 색채로 10대 문화를 사로잡았다.',
    popularity: 90,
    rating: 4.5,
    rarity: 'Common',
  },

  // ── Super Famicom / SNES ──
  {
    id: 'g11',
    title: 'Chrono Trigger',
    releaseYear: 1995,
    releaseDate: '1995-03-11',
    platform: 'Super Famicom',
    genre: 'RPG',
    country: 'JP',
    developer: 'Square (Dream Team)',
    publisher: 'Square',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '드래곤퀘스트와 파이널판타지의 크리에이터가 합작한 시간여행 RPG의 최고봉.',
    historicalContext: '호리이 유지, 사카구치 히로노부, 토리야마 아키라가 모인 "드림팀"의 걸작. 13개의 멀티 엔딩.',
    historicalNote: '13개의 멀티 엔딩, 드림팀 개발작',
    competingPlatforms: ['PlayStation', 'Sega Saturn'],
    sameEraGames: ['g12', 'g13', 'g14'],
    popularity: 94,
    rating: 4.9,
    rarity: 'Rare',
  },
  {
    id: 'g12',
    title: 'Super Metroid',
    releaseYear: 1994,
    releaseDate: '1994-03-19',
    platform: 'Super Famicom',
    genre: 'Action',
    country: 'JP',
    developer: 'Nintendo R&D1',
    publisher: 'Nintendo',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '메트로이드배니아 장르의 정점. 탐험과 액션의 완벽한 융합.',
    historicalContext: '"Super Metroid" 오프닝 나레이션은 게임 스토리텔링 역사에 남는 명문. 외로운 행성 탐험의 고독감.',
    popularity: 88,
    rating: 4.8,
    rarity: 'Uncommon',
  },
  {
    id: 'g13',
    title: 'Final Fantasy VI',
    releaseYear: 1994,
    releaseDate: '1994-04-02',
    platform: 'Super Famicom',
    genre: 'RPG',
    country: 'JP',
    developer: 'Square',
    publisher: 'Square',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '2D RPG의 최고봉. 오페라 장면과 케프카의 광기로 기억되는 걸작.',
    historicalContext: '케프카는 게임 역사상 가장 완성도 높은 악당 중 하나. 오페라 장면은 2D 시대 최고의 연출.',
    popularity: 93,
    rating: 4.9,
    rarity: 'Rare',
  },
  {
    id: 'g14',
    title: 'Super Mario World',
    releaseYear: 1990,
    releaseDate: '1990-11-21',
    platform: 'Super Famicom',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '요시의 첫 등장과 96개의 출구. 슈퍼 패미컴의 론칭 타이틀이자 2D 마리오의 정점.',
    historicalContext: '요시는 이후 닌텐도의 핵심 캐릭터로 자리잡았다. 스타 월드와 특수 스테이지의 숨겨진 깊이.',
    popularity: 96,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g34',
    title: 'EarthBound',
    releaseYear: 1994,
    releaseDate: '1994-08-27',
    platform: 'Super Famicom',
    genre: 'RPG',
    country: 'JP',
    developer: 'Ape / HAL Laboratory',
    publisher: 'Nintendo',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: '현대 사회를 배경으로 한 유니크한 RPG. 발매 당시 저조한 판매에서 컬트 클래식으로 재평가.',
    historicalContext: '이토이 시게사토 감독. "어머니 2" 프로젝트. 팬들의 열정으로 닌텐도가 해외 발매를 결정.',
    historicalNote: '컬트 클래식 → 닌텐도 역대 명작 재평가',
    popularity: 85,
    rating: 4.7,
    rarity: 'Legendary',
  },
  {
    id: 'g_smrpg',
    title: 'Super Mario RPG',
    releaseYear: 1996,
    releaseDate: '1996-03-09',
    platform: 'Super Famicom',
    genre: 'RPG',
    country: 'JP',
    developer: 'Square',
    publisher: 'Nintendo',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: 'Square와 Nintendo의 이례적 협작. 마리오 세계관 최초의 RPG.',
    historicalContext: 'Square가 닌텐도와 결별하기 전 마지막 슈퍼패미컴 협작. 이후 Square는 PS1 진영으로 이동.',
    popularity: 80,
    rating: 4.5,
    rarity: 'Uncommon',
  },

  // ── PlayStation ──
  {
    id: 'g15',
    title: 'Final Fantasy VII',
    releaseYear: 1997,
    releaseDate: '1997-01-31',
    platform: 'PlayStation',
    genre: 'RPG',
    country: 'JP',
    developer: 'Square',
    publisher: 'Square',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: 'RPG를 대중 문화로 끌어올린 혁명적 작품. 에어리스의 죽음은 게임 역사의 전환점.',
    historicalContext: '노무라 테츠야의 캐릭터 디자인, 우에마츠 노부오의 음악. 3장의 CD-ROM에 담긴 서사시.',
    historicalNote: '에어리스의 죽음 — 게임 스토리텔링의 전환점',
    competingPlatforms: ['Nintendo 64', 'Sega Saturn'],
    popularity: 97,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g16',
    title: 'Metal Gear Solid',
    releaseYear: 1998,
    releaseDate: '1998-09-03',
    platform: 'PlayStation',
    genre: 'Stealth Action',
    country: 'JP',
    developer: 'Konami (Kojima Productions)',
    publisher: 'Konami',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '스텔스 액션과 시네마틱 스토리텔링의 완벽한 결합. 코지마 히데오의 대표작.',
    historicalContext: '사이코 만티스가 메모리 카드를 읽고 컨트롤러 포트를 바꾸는 메타 연출. 게임 언어의 혁신.',
    popularity: 94,
    rating: 4.8,
    rarity: 'Common',
  },
  {
    id: 'g17',
    title: 'Castlevania: Symphony of the Night',
    releaseYear: 1997,
    releaseDate: '1997-03-20',
    platform: 'PlayStation',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Konami',
    publisher: 'Konami',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '메트로이드배니아 장르에 이름을 부여한 역사적 작품. 거꾸로 된 성의 충격.',
    historicalContext: '"What is a man? A miserable little pile of secrets!" — 역사상 가장 유명한 게임 대사 중 하나.',
    popularity: 91,
    rating: 4.9,
    rarity: 'Rare',
  },
  {
    id: 'g_re1',
    title: 'Resident Evil',
    releaseYear: 1996,
    releaseDate: '1996-03-22',
    platform: 'PlayStation',
    genre: 'Survival Horror',
    country: 'JP',
    developer: 'Capcom',
    publisher: 'Capcom',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '바이오하자드 시리즈의 출발점. 서바이벌 호러 장르를 정의한 공포의 고전.',
    historicalContext: '"Jill Sandwich" 같은 B급 영문 더빙이 역설적으로 컬트적 인기를 얻었다.',
    popularity: 86,
    rating: 4.4,
    rarity: 'Uncommon',
  },

  // ── Nintendo 64 ──
  {
    id: 'g18',
    title: 'Super Mario 64',
    releaseYear: 1996,
    releaseDate: '1996-06-23',
    platform: 'Nintendo 64',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '3D 플랫포머의 기준을 세운 혁명적 작품. 아날로그 스틱으로 새로운 조작 패러다임 창조.',
    historicalContext: 'N64 론칭 타이틀로 3D 게임의 표준을 확립. "It\'s-a Me, Mario!" 음성 더빙의 충격.',
    popularity: 96,
    rating: 4.8,
    rarity: 'Common',
  },
  {
    id: 'g19',
    title: 'The Legend of Zelda: Ocarina of Time',
    releaseYear: 1998,
    releaseDate: '1998-11-21',
    platform: 'Nintendo 64',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '다수 매체에서 역대 최고의 게임으로 선정. Z-타겟팅 시스템으로 3D 전투의 표준을 제시.',
    historicalContext: 'Z-타겟팅, 시간의 흐름을 이용한 퍼즐, 웅장한 오케스트라 사운드. 게임 예술의 정점.',
    popularity: 99,
    rating: 5.0,
    rarity: 'Common',
  },
  {
    id: 'g20',
    title: 'GoldenEye 007',
    releaseYear: 1997,
    releaseDate: '1997-08-25',
    platform: 'Nintendo 64',
    genre: 'FPS',
    country: 'GB',
    developer: 'Rare',
    publisher: 'Nintendo',
    era: '5th Gen (1993-2006)',
    imageUrl: '',
    description: '콘솔 FPS의 가능성을 입증한 작품. 4인 분할 화면 대전의 추억.',
    historicalContext: '2인 이상 분할 화면 멀티플레이를 콘솔 FPS에서 대중화. 007 라이선스 게임 중 역대 최고.',
    popularity: 89,
    rating: 4.7,
    rarity: 'Uncommon',
  },

  // ── Dreamcast ──
  {
    id: 'g21',
    title: 'Shenmue',
    releaseYear: 1999,
    releaseDate: '1999-12-29',
    platform: 'Dreamcast',
    genre: 'Action Adventure',
    country: 'JP',
    developer: 'Sega AM2',
    publisher: 'Sega',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '오픈월드와 QTE의 선구자. 당시 역대 최고 제작비로 게임의 미래를 보여주다.',
    historicalContext: '스즈키 유의 $70M 개발비 투자. 당시 게임 역사상 최대 규모. GTA에 영향을 준 오픈 세계.',
    historicalNote: '당시 최고 제작비 $47M 투자',
    popularity: 82,
    rating: 4.5,
    rarity: 'Rare',
  },
  {
    id: 'g22',
    title: 'Sonic Adventure',
    releaseYear: 1998,
    releaseDate: '1998-12-23',
    platform: 'Dreamcast',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Sonic Team (Sega)',
    publisher: 'Sega',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '소닉의 3D 전환을 이끈 드림캐스트의 킬러 타이틀.',
    historicalContext: '첫 소닉 어드벤처 게임. Live & Learn OST는 소닉 시리즈 최고의 음악으로 꼽힌다.',
    popularity: 78,
    rating: 4.2,
    rarity: 'Uncommon',
  },
  {
    id: 'g23',
    title: 'Jet Set Radio',
    releaseYear: 2000,
    releaseDate: '2000-06-29',
    platform: 'Dreamcast',
    genre: 'Action',
    country: 'JP',
    developer: 'Hitmaker (Sega)',
    publisher: 'Sega',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '셀 셰이딩 그래픽의 선구자. 독특한 아트 스타일과 사운드트랙으로 컬트적 인기.',
    historicalContext: '롤러블레이드 + 그라피티 + 일본 도시 문화의 융합. 비트 시대 스타일의 정수.',
    popularity: 75,
    rating: 4.4,
    rarity: 'Rare',
  },
  {
    id: 'g35',
    title: 'Panzer Dragoon Saga',
    releaseYear: 1998,
    releaseDate: '1998-01-29',
    platform: 'Dreamcast',
    genre: 'RPG',
    country: 'JP',
    developer: 'Team Andromeda (Sega)',
    publisher: 'Sega',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '세가 새턴 말기의 희귀 RPG 걸작. 극소량 생산으로 최고급 희귀 게임 중 하나.',
    historicalContext: '세가 새턴 단독 발매. 북미 30,000장 한정. 중고가 수십만 원을 호가하는 전설의 희귀작.',
    popularity: 70,
    rating: 4.7,
    rarity: 'Legendary',
  },

  // ── PlayStation 2 ──
  {
    id: 'g24',
    title: 'Shadow of the Colossus',
    releaseYear: 2005,
    releaseDate: '2005-10-18',
    platform: 'PlayStation 2',
    genre: 'Action Adventure',
    country: 'JP',
    developer: 'Team Ico (Sony)',
    publisher: 'Sony',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '게임의 예술적 가능성을 증명한 걸작. 16개의 거상과의 전투만으로 깊은 감동을 전달.',
    historicalContext: '"게임은 예술인가?" 논쟁에서 항상 첫 번째로 언급되는 작품. 우에다 후미토 감독.',
    popularity: 91,
    rating: 4.9,
    rarity: 'Uncommon',
  },
  {
    id: 'g25',
    title: 'Grand Theft Auto: San Andreas',
    releaseYear: 2004,
    releaseDate: '2004-10-26',
    platform: 'PlayStation 2',
    genre: 'Action Adventure',
    country: 'US',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '오픈월드 게임의 규모를 한 차원 높인 작품. 세 도시를 아우르는 거대한 세계.',
    historicalContext: '27.5M 장 판매. 당시 가장 큰 오픈월드 맵, 수영/자전거/비행기 조작 추가.',
    popularity: 93,
    rating: 4.7,
    rarity: 'Common',
  },
  {
    id: 'g26',
    title: 'Persona 4',
    releaseYear: 2008,
    releaseDate: '2008-07-10',
    platform: 'PlayStation 2',
    genre: 'RPG',
    country: 'JP',
    developer: 'Atlus',
    publisher: 'Atlus',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '일상 시뮬레이션과 던전 RPG의 완벽한 조화. 페르소나 시리즈를 대중화시킨 명작.',
    historicalContext: 'PS2 말기에 등장한 JRPG의 걸작. 방영 이후 애니메이션, 음악, 아레나 격투 게임으로 확장.',
    popularity: 89,
    rating: 4.8,
    rarity: 'Uncommon',
  },
  {
    id: 'g_ico',
    title: 'Ico',
    releaseYear: 2001,
    releaseDate: '2001-09-24',
    platform: 'PlayStation 2',
    genre: 'Action Adventure',
    country: 'JP',
    developer: 'Team Ico (Sony)',
    publisher: 'Sony',
    era: '6th Gen (1998-2013)',
    imageUrl: '',
    description: '소년과 소녀의 손잡기. 미니멀한 스토리텔링으로 감동을 전달한 예술적 게임.',
    historicalContext: '우에다 후미토의 데뷔작. Shadow of the Colossus의 전신. 손잡기 메커닉의 감성적 혁신.',
    popularity: 78,
    rating: 4.6,
    rarity: 'Rare',
  },

  // ── Nintendo DS ──
  {
    id: 'g27',
    title: 'Phoenix Wright: Ace Attorney',
    releaseYear: 2005,
    releaseDate: '2005-10-12',
    platform: 'Nintendo DS',
    genre: 'Visual Novel',
    country: 'JP',
    developer: 'Capcom',
    publisher: 'Capcom',
    era: '7th Gen (2005-2017)',
    imageUrl: '',
    description: '법정 어드벤처의 걸작. "이의 있습니다!" 터치 조작으로 DS의 매력을 극대화.',
    historicalContext: '나루호도 류이치(나루호도=成歩堂)의 이름 유래: 納得(납득). 법정 드라마와 추리의 완벽한 결합.',
    popularity: 83,
    rating: 4.6,
    rarity: 'Uncommon',
  },
  {
    id: 'g28',
    title: 'The World Ends with You',
    releaseYear: 2007,
    releaseDate: '2007-07-27',
    platform: 'Nintendo DS',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Square Enix / Jupiter',
    publisher: 'Square Enix',
    era: '7th Gen (2005-2017)',
    imageUrl: '',
    description: '시부야를 무대로 한 스타일리시 액션 RPG. DS의 듀얼 스크린을 활용한 독창적 전투.',
    historicalContext: '시부야 패션, 음악, 문화를 게임 안에 담은 청춘 RPG. 고나가이 타카에히로의 음악.',
    popularity: 79,
    rating: 4.7,
    rarity: 'Rare',
  },
  {
    id: 'g29',
    title: 'Pokémon HeartGold / SoulSilver',
    releaseYear: 2009,
    releaseDate: '2009-09-12',
    platform: 'Nintendo DS',
    genre: 'RPG',
    country: 'JP',
    developer: 'Game Freak',
    publisher: 'Nintendo',
    era: '7th Gen (2005-2017)',
    imageUrl: '',
    description: '포켓몬 2세대의 완벽한 리메이크. 포켓워커 연동과 따라오는 포켓몬 기능.',
    historicalContext: '포켓워커 만보계 연동, 493마리 포켓몬, 칸토 지방 추가로 역대 최고 볼륨의 포켓몬 게임.',
    popularity: 88,
    rating: 4.8,
    rarity: 'Uncommon',
  },

  // ── Nintendo Switch ──
  {
    id: 'g30',
    title: 'The Legend of Zelda: Breath of the Wild',
    releaseYear: 2017,
    releaseDate: '2017-03-03',
    platform: 'Nintendo Switch',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    era: '8th Gen (2012-2020)',
    imageUrl: '',
    description: '오픈월드 게임의 새로운 패러다임. 물리 엔진 기반의 자유도 높은 탐험과 전투.',
    historicalContext: '물리 기반 인터랙션, 내구도 시스템, 코로크 씨앗 900개. 젤다 시리즈의 완전한 재창조.',
    popularity: 97,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g31',
    title: 'Hollow Knight',
    releaseYear: 2018,
    releaseDate: '2018-06-12',
    platform: 'Nintendo Switch',
    genre: 'Action',
    country: 'AU',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    era: '8th Gen (2012-2020)',
    imageUrl: '',
    description: '인디 메트로이드배니아의 걸작. 아름다운 아트와 도전적인 난이도의 완벽한 조화.',
    historicalContext: '3인 팀 "Team Cherry"가 5년 제작. 킥스타터 $57K 목표로 시작, 현재 수백만 장 판매.',
    popularity: 88,
    rating: 4.8,
    rarity: 'Common',
  },
  {
    id: 'g32',
    title: 'Celeste',
    releaseYear: 2018,
    releaseDate: '2018-01-25',
    platform: 'Nintendo Switch',
    genre: 'Platformer',
    country: 'CA',
    developer: 'Maddy Thorson & Noel Berry',
    publisher: 'Matt Makes Games',
    era: '8th Gen (2012-2020)',
    imageUrl: '',
    description: '정밀 플랫포머의 정수. 정신 건강을 주제로 한 감동적인 스토리와 완벽한 레벨 디자인.',
    historicalContext: '개발자의 실제 불안장애 경험이 녹아든 게임. "어시스트 모드"로 접근성에 대한 새 기준.',
    popularity: 85,
    rating: 4.8,
    rarity: 'Common',
  },
  {
    id: 'g33',
    title: 'Fire Emblem: Three Houses',
    releaseYear: 2019,
    releaseDate: '2019-07-26',
    platform: 'Nintendo Switch',
    genre: 'Strategy RPG',
    country: 'JP',
    developer: 'Intelligent Systems / Koei Tecmo',
    publisher: 'Nintendo',
    era: '8th Gen (2012-2020)',
    imageUrl: '',
    description: '학원 시뮬레이션과 전략 RPG의 결합. 세 학급의 스토리로 높은 리플레이 가치.',
    popularity: 86,
    rating: 4.7,
    rarity: 'Common',
  },
  {
    id: 'g_totk',
    title: 'The Legend of Zelda: Tears of the Kingdom',
    releaseYear: 2023,
    releaseDate: '2023-05-12',
    platform: 'Nintendo Switch',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    era: '9th Gen (2020-)',
    imageUrl: '',
    description: 'BotW를 넘어선 3차원 자유도. 하늘, 지하, 지상의 3개 레이어 오픈월드.',
    historicalContext: '울트라핸드, 스카이워드, 리콜, 패서블 4가지 능력으로 무한한 창의적 문제 해결.',
    popularity: 95,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g_astro',
    title: 'Astro Bot',
    releaseYear: 2024,
    releaseDate: '2024-09-06',
    platform: 'PlayStation 5',
    genre: 'Platformer',
    country: 'JP',
    developer: 'Team Asobi (Sony)',
    publisher: 'Sony',
    era: '9th Gen (2020-)',
    imageUrl: '',
    description: '2024 GOTY. Sony 역사에 대한 오마주와 완벽한 게임플레이의 조화.',
    historicalContext: '플레이스테이션 30주년을 기념하는 캐릭터들의 카메오. 미야모토 시게루도 극찬한 작품.',
    popularity: 94,
    rating: 4.9,
    rarity: 'Common',
  },
  {
    id: 'g_splatoon',
    title: 'Splatoon 3',
    releaseYear: 2022,
    releaseDate: '2022-09-09',
    platform: 'Nintendo Switch',
    genre: 'TPS',
    country: 'JP',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    era: '8th Gen (2012-2020)',
    imageUrl: '',
    description: '잉크 사수 게임의 3번째 진화. 살몬런 오버타임 추가와 풍부한 배틀 모드.',
    popularity: 82,
    rating: 4.4,
    rarity: 'Common',
  },
  {
    id: 'g_darksouls',
    title: 'Dark Souls',
    releaseYear: 2011,
    releaseDate: '2011-09-22',
    platform: 'PlayStation 3',
    genre: 'Action RPG',
    country: 'JP',
    developer: 'FromSoftware',
    publisher: 'Namco Bandai',
    era: '7th Gen (2005-2017)',
    imageUrl: '',
    description: '소울스라이크 장르의 시조. "당신은 죽었습니다" 문구로 기억되는 도전의 게임.',
    historicalContext: '"Prepare to Die" 에디션. 미야자키 히데타카의 독특한 스토리텔링 방식이 장르를 창조.',
    popularity: 92,
    rating: 4.8,
    rarity: 'Uncommon',
  },
  {
    id: 'g_minecraft',
    title: 'Minecraft',
    releaseYear: 2011,
    releaseDate: '2011-11-18',
    platform: 'PC',
    genre: 'Sandbox',
    country: 'SE',
    developer: 'Mojang Studios',
    publisher: 'Microsoft',
    era: '7th Gen (2005-2017)',
    imageUrl: '',
    description: '역대 가장 많이 팔린 게임. 무한한 창의성의 레고 블록 세계.',
    historicalContext: 'Notch(Marcus Persson) 1인 개발로 시작. 2014년 MS가 $2.5B에 인수. 3억 장+ 판매.',
    popularity: 99,
    rating: 4.7,
    rarity: 'Common',
  },
  {
    id: 'g_doom',
    title: 'DOOM',
    releaseYear: 1993,
    releaseDate: '1993-12-10',
    platform: 'PC',
    genre: 'FPS',
    country: 'US',
    developer: 'id Software',
    publisher: 'id Software',
    era: '4th Gen (1987-2004)',
    imageUrl: '',
    description: 'FPS 장르를 정의한 전설. "DOOM이 실행되면 DOOM을 실행한다"는 밈의 원조.',
    historicalContext: 'John Carmack의 id Tech 엔진으로 쿼터뷰 → FPS 혁명. 비폭력 논란으로 게임 등급제 탄생.',
    popularity: 90,
    rating: 4.7,
    rarity: 'Uncommon',
  },
  {
    id: 'g_acnh',
    title: 'Animal Crossing: New Horizons',
    releaseYear: 2020,
    releaseDate: '2020-03-20',
    platform: 'Nintendo Switch',
    genre: 'Simulation',
    country: 'JP',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    era: '9th Gen (2020-)',
    imageUrl: '',
    description: 'COVID-19 팬데믹 시대의 안식처. 무인도 개발 시뮬레이션의 힐링.',
    historicalContext: '코로나 봉쇄 기간 중 발매. 정치인들이 선거 유세를 하고 결혼식이 치러진 가상 공간.',
    popularity: 92,
    rating: 4.6,
    rarity: 'Common',
  },
];

// ─── COLLECTION ITEMS (12+) ───────────────────────────────────────────────────

export const defaultCollectionItems: CollectionItem[] = [
  {
    id: 'c01', gameId: 'g04',
    status: '패키지 보유', ownershipStatus: '패키지 보유',
    purchaseType: '패키지', condition: 'Good', region: 'JPN',
    purchaseDate: '2020-03-15', purchasePrice: 85000,
    memo: '어릴 적 첫 게임. 박스 상태 양호. 설명서 있음.',
    playStartDate: '1995-01-01', clearDate: '1995-03-01', playTime: 30,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c02', gameId: 'g11',
    status: '미개봉', ownershipStatus: '미개봉',
    purchaseType: '패키지', condition: 'Mint', region: 'JPN',
    purchaseDate: '2023-11-20', purchasePrice: 320000,
    memo: '일본판 미개봉 수집. 보존 상태 완벽. 투명 필름 유지.',
    rating: 5, visibility: 'public',
  },
  {
    id: 'c03', gameId: 'g15',
    status: '엔딩 완료', ownershipStatus: '엔딩 완료',
    purchaseType: '다운로드', condition: 'Good', region: 'KOR',
    purchaseDate: '2019-06-01', purchasePrice: 45000,
    memo: '세 번째 클리어. 에어리스 루트는 매번 울린다.',
    playStartDate: '2019-06-05', clearDate: '2019-07-10', playTime: 52,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c04', gameId: 'g19',
    status: '엔딩 완료', ownershipStatus: '엔딩 완료',
    purchaseType: '패키지', condition: 'Excellent', region: 'KOR',
    purchaseDate: '2018-12-25', purchasePrice: 0,
    memo: '크리스마스 선물로 받은 추억의 게임. 포장지 보관 중.',
    playStartDate: '2019-01-01', clearDate: '2019-02-14', playTime: 45,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c05', gameId: 'g30',
    status: '플레이 중', ownershipStatus: '플레이 중',
    purchaseType: '패키지', condition: 'Excellent', region: 'KOR',
    purchaseDate: '2024-01-10', purchasePrice: 62000,
    memo: '코로그 씨앗 수집 중. 현재 450개. 완전 정복 도전.',
    playStartDate: '2024-01-12', playTime: 120,
    rating: 4, visibility: 'public',
  },
  {
    id: 'c06', gameId: 'g08',
    status: '단품 보유', ownershipStatus: '단품 보유',
    purchaseType: '패키지', condition: 'Fair', region: 'KOR',
    purchaseDate: '2021-07-08', purchasePrice: 18000,
    memo: '카트리지만 보유. 라벨 약간 벗겨짐.',
    playStartDate: '2021-07-10', playTime: 8,
    rating: 4, visibility: 'friends',
  },
  {
    id: 'c07', gameId: 'g21',
    status: '패키지 보유', ownershipStatus: '패키지 보유',
    purchaseType: '패키지', condition: 'Excellent', region: 'JPN',
    purchaseDate: '2022-09-14', purchasePrice: 180000,
    memo: '드림캐스트 컬렉션의 자랑. 설명서 포함 완품. GD-ROM 상태 양호.',
    rating: 4, visibility: 'public',
  },
  {
    id: 'c08', gameId: 'g24',
    status: '엔딩 완료', ownershipStatus: '엔딩 완료',
    purchaseType: '패키지', condition: 'Good', region: 'KOR',
    purchaseDate: '2020-05-20', purchasePrice: 35000,
    memo: '아구로의 마지막 거상전은 압도적이었다. 2회차 진행 예정.',
    playStartDate: '2020-05-22', clearDate: '2020-06-01', playTime: 12,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c09', gameId: 'g34',
    status: '패키지 보유', ownershipStatus: '패키지 보유',
    purchaseType: '패키지', condition: 'Excellent', region: 'JPN',
    purchaseDate: '2023-04-02', purchasePrice: 580000,
    memo: '레전더리 등급! 일본판 완품. 최고의 수집품. MOTHER2 원판.',
    rating: 5, visibility: 'public',
  },
  {
    id: 'c10', gameId: 'g17',
    status: '위시리스트', ownershipStatus: '위시리스트',
    purchaseDate: '',
    memo: '블랙 라벨 버전을 찾고 있음. 가격 감시 중. 목표 15만원 이하.',
    rating: 0, visibility: 'private',
  },
  {
    id: 'c11', gameId: 'g13',
    status: '플레이 중', ownershipStatus: '플레이 중',
    purchaseType: '패키지', condition: 'Good', region: 'JPN',
    purchaseDate: '2024-02-14', purchasePrice: 95000,
    memo: '첫 플레이. 케프카의 매력에 빠지는 중. 오페라 씬 감동.',
    playStartDate: '2024-02-15', playTime: 25,
    rating: 4, visibility: 'public',
  },
  {
    id: 'c12', gameId: 'g31',
    status: '엔딩 완료', ownershipStatus: '엔딩 완료',
    purchaseType: '패키지', condition: 'Excellent', region: 'KOR',
    purchaseDate: '2023-08-30', purchasePrice: 38000,
    memo: '진 엔딩까지 클리어. 판테온은 포기... 언젠가 도전할 것.',
    playStartDate: '2023-09-01', clearDate: '2023-10-15', playTime: 65,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c13', gameId: 'g16',
    status: '엔딩 완료', ownershipStatus: '엔딩 완료',
    purchaseType: '패키지', condition: 'Good', region: 'KOR',
    purchaseDate: '2022-03-10', purchasePrice: 28000,
    memo: '사이코 만티스 씬에서 충격받음. 2번 엔딩 모두 클리어.',
    playStartDate: '2022-03-12', clearDate: '2022-04-01', playTime: 18,
    rating: 5, visibility: 'public',
  },
  {
    id: 'c14', gameId: 'g_sonic1',
    status: '단품 보유', ownershipStatus: '단품 보유',
    purchaseType: '패키지', condition: 'Fair', region: 'KOR',
    purchaseDate: '2021-05-15', purchasePrice: 22000,
    memo: '메가드라이브 컬렉션 입문작. 카트리지 상태 Fair.',
    playTime: 5,
    rating: 3, visibility: 'friends',
  },
];

// ─── TIMELINE EVENTS ──────────────────────────────────────────────────────────

export const timelineEvents: any[] = [
  { year: 1972, title: 'Magnavox Odyssey', type: 'console', description: '세계 최초의 가정용 비디오 게임 콘솔. Ralph Baer 설계.', imageUrl: '', innovation: '가정에서 TV로 게임을 즐기는 시대의 시작', relatedGameCount: 0, era: '1st Gen (1972-1980)' },
  { year: 1977, title: 'Atari 2600', type: 'console', description: '교체형 카트리지 시스템으로 게임기 시장 대중화', imageUrl: '', innovation: 'ROM 카트리지 교체 시스템 도입', relatedGameCount: 3, era: '2nd Gen (1976-1992)' },
  { year: 1980, title: 'Pac-Man (아케이드)', type: 'game', description: '최초의 글로벌 게임 문화 현상. 팩맨 패션, 음악, 애니메이션으로 확장', imageUrl: '', innovation: '미로 탈출 + 아이템 수집 메커닉', relatedGameCount: 0, era: '2nd Gen (1976-1992)' },
  { year: 1983, title: 'Nintendo Famicom / NES', type: 'console', description: '비디오 게임 대붕괴 이후 산업 부활의 주역', imageUrl: '', innovation: 'D-패드와 A/B 버튼 배치의 표준화, 라이선스 품질 관리', relatedGameCount: 5, era: '3rd Gen (1983-2003)' },
  { year: 1983, title: '비디오 게임 대붕괴', type: 'event', description: '북미 게임 시장 매출이 $3.2B → $100M으로 붕괴. E.T.가 그 상징.', imageUrl: '', innovation: '이후 닌텐도의 라이선스 제도가 품질 기준을 세우는 계기', relatedGameCount: 0, era: '3rd Gen (1983-2003)' },
  { year: 1985, title: 'Super Mario Bros.', type: 'game', description: '사이드스크롤 플랫포머의 기준을 제시', imageUrl: '', innovation: '스크롤링 스테이지와 파워업 시스템', relatedGameCount: 0, era: '3rd Gen (1983-2003)' },
  { year: 1989, title: 'Game Boy + Tetris', type: 'console', description: '휴대용 게임의 시대를 열다. 테트리스 번들로 118M 대 판매.', imageUrl: '', innovation: '장시간 배터리와 통신 케이블 교환', relatedGameCount: 3, era: '4th Gen (1987-2004)' },
  { year: 1990, title: 'Super Famicom', type: 'console', description: '16비트의 황금기. RPG와 액션의 명작들이 쏟아지다.', imageUrl: '', innovation: 'Mode 7 회전/확대 효과와 Sony SPC700 사운드 칩', relatedGameCount: 6, era: '4th Gen (1987-2004)' },
  { year: 1993, title: 'DOOM', type: 'game', description: 'FPS 장르를 창시. 폭력성 논란으로 게임 등급제 탄생.', imageUrl: '', innovation: 'id Tech 엔진으로 유사 3D 렌더링 혁신', relatedGameCount: 0, era: '4th Gen (1987-2004)' },
  { year: 1994, title: 'PlayStation', type: 'console', description: 'CD-ROM으로 3D 게임의 시대를 열다', imageUrl: '', innovation: 'CD-ROM 기반 대용량 저장과 3D 폴리곤 렌더링', relatedGameCount: 5, era: '5th Gen (1993-2006)' },
  { year: 1996, title: 'Nintendo 64', type: 'console', description: '아날로그 스틱과 3D 게임의 혁신', imageUrl: '', innovation: '아날로그 스틱, 트리거 버튼, 럼블 팩', relatedGameCount: 4, era: '5th Gen (1993-2006)' },
  { year: 1997, title: 'Final Fantasy VII', type: 'game', description: 'RPG를 대중 문화의 반열에 올리다', imageUrl: '', innovation: '3D 시네마틱 컷씬과 FMV 연출', relatedGameCount: 0, era: '5th Gen (1993-2006)' },
  { year: 1998, title: 'The Legend of Zelda: Ocarina of Time', type: 'game', description: '역대 최고 게임 평점 99점. Z-타겟팅으로 3D 전투 표준화.', imageUrl: '', innovation: 'Z-타겟팅 전투 시스템, 음악 기반 퍼즐', relatedGameCount: 0, era: '5th Gen (1993-2006)' },
  { year: 1998, title: 'Dreamcast', type: 'console', description: '온라인 게임의 선구자. 세가 마지막 콘솔.', imageUrl: '', innovation: '내장 56k 모뎀과 VMU 서브 스크린', relatedGameCount: 4, era: '6th Gen (1998-2013)' },
  { year: 2000, title: 'PlayStation 2', type: 'console', description: '역대 가장 많이 팔린 게임 콘솔 (155M 대)', imageUrl: '', innovation: 'DVD 재생과 후방 호환성, Emotion Engine', relatedGameCount: 4, era: '6th Gen (1998-2013)' },
  { year: 2004, title: 'Nintendo DS', type: 'console', description: '듀얼 스크린과 터치의 혁신 (154M 대)', imageUrl: '', innovation: '듀얼 스크린, 터치 입력, 마이크 활용', relatedGameCount: 3, era: '7th Gen (2005-2017)' },
  { year: 2011, title: 'Dark Souls', type: 'game', description: '소울스라이크 장르의 탄생. 도전과 성취의 새로운 게임 언어.', imageUrl: '', innovation: '사망 페널티와 메시지 시스템으로 새 장르 창조', relatedGameCount: 0, era: '7th Gen (2005-2017)' },
  { year: 2011, title: 'Minecraft 정식 출시', type: 'game', description: '역대 최다 판매 게임 (3억+). 창의성과 서바이벌의 융합.', imageUrl: '', innovation: '절차적 세계 생성과 무한한 크리에이티브 모드', relatedGameCount: 0, era: '7th Gen (2005-2017)' },
  { year: 2017, title: 'Nintendo Switch', type: 'console', description: '거치형과 휴대형의 경계를 허물다', imageUrl: '', innovation: '하이브리드 콘솔, Joy-Con 분리 합체', relatedGameCount: 6, era: '8th Gen (2012-2020)' },
  { year: 2017, title: 'Breath of the Wild', type: 'game', description: '오픈월드의 새로운 기준. 5관왕 GOTY.', imageUrl: '', innovation: '물리 기반 인터랙션과 비선형 탐험', relatedGameCount: 0, era: '8th Gen (2012-2020)' },
  { year: 2020, title: 'PS5 / Xbox Series X', type: 'console', description: '9세대 콘솔의 시작. SSD로 로딩 시간 혁신.', imageUrl: '', innovation: 'NVMe SSD, 레이트레이싱, 120fps 지원', relatedGameCount: 1, era: '9th Gen (2020-)' },
];
